# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Sharpening Tools
tagline:          'The love of programming'
description:      'Honing programming skills and trying to not cut myself (too much) along the way.'
url:              http://www.beta.com
baseurl:          '/'
paginate:         5

author:
  name:           'Stephane Liu'
  url:            https://twitter.com/stephaneliu

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/stephaneliu
