# Site settings
title: Your awesome title
email: your-email@domain.com
description: I practice in Ruby. I have a passion to learn all things Ruby, Ruby on Rails and the tools to sharpen my skills.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stephaneliu
github_username:  stephaneliu

# Build settings
markdown: kramdown
